app/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path("", homepage, name=""),
    path("home/", homepage, name="home"),
    path("about/", aboutpage, name="about"),
    path("service/", servicepage, name="service"),
    path("contact/", contactpage, name="contact"),
    path("register/", registerpage, name="register"),
    path("login/", loginpage, name="login"),
    path("logout/", logoutpage, name="logout"),
    path("registerdata/", registerdatapage, name="registerdata"),
    path("logindata/", logindatapage, name="logindata"),
    path("dash/", dashpage, name="dash"),
    path("querydata/", querydatapage, name="querydata"),
    path("shawtabledatabtn/", shawtabledatabtnpage, name="shawtabledatabtn"),
    path("EditDeleteData/", EditDeleteDatapage, name="EditDeleteData"),
]

app/models.py
from django.db import models

# Create your models here.

class StudentModelRegistration(models.Model) :
    Name = models.CharField(max_length=200)
    Phone = models.IntegerField()
    Email = models.EmailField(max_length=254)
    Password = models.CharField(max_length=100)
    Confirm_Password = models.CharField(max_length=100, null=True)
    
class StudentQuery(models.Model):
    Query_Email = models.EmailField(max_length=254)
    Query_Sub = models.CharField(max_length=300)
    QueryDate = models.DateTimeField()
    Query_Query = models.CharField(max_length=1000)

app/forms.py
from django import forms
from .models import StudentModelRegistration

class StudentFormRegistration(forms.ModelForm) :
    class Meta :
        model = StudentModelRegistration
        fields = "__all__"


class LoginForm(forms.Form) :
    Email = forms.EmailField(label='Email ', max_length=200, required=True)
    Password = forms.CharField(label="Password ", max_length=100, required=True)

class StudentQueryForm(forms.Form):
    Query_Email = forms.EmailField(label="Email ", required=True)
    Query_Subject = forms.CharField(label="Subject ", max_length=200, required=True)
    Query = forms.CharField(widget=forms.Textarea, label="Query")

app/views.py
import datetime
from django.http import HttpResponse
from django.shortcuts import render, redirect
from .forms import StudentFormRegistration, LoginForm, StudentQueryForm
from .models import StudentModelRegistration, StudentQuery
# Create your views here.

def homepage(request) :
    try:
        user_name = request.session['NAME']
        return render(request, "app1/index.html", {"name" : user_name, "btn" : ""})
    except :
        return render(request, "app1/index.html", {"btn" : "RLol"})

def aboutpage(request) :
    try:
        user_name = request.session['NAME']
        return render(request, "app1/about.html", {"name" : user_name, "btn" : "" })
    except :
        return render(request, "app1/about.html", {"btn" : "RLol"})

    
       
def servicepage(request) :
    try :
        user_name = request.session['NAME']
        return render(request, "app1/service.html", {"name" : user_name, "btn" : ""})
    except :
        return render(request, "app1/service.html", {"btn" : "RLol"})
    
 
def contactpage(request) :
    try:
        user_name = request.session['NAME']
        return render(request, "app1/contact.html", {"name" : user_name, "btn" : "" })
    except:
        return render(request, "app1/contact.html", {"btn" : "RLol"})
    
def registerpage(request) :
    form = {}
    form["key"] = StudentFormRegistration
    return render(request, "app1/registration.html", {"formdata" : form, "btn" : "RLol"})

def loginpage(request) :
    form = {}
    form['key'] = LoginForm
    return render(request, "app1/login.html", {"formdata" : form, "btn" : "RLol"})

def logoutpage(request) :
    request.session.flush()
    return render(request, "app1/index.html", {"btn" : "RLol"})
   

def registerdatapage(request) :
    if request.POST :
        print("Inside")
        name = request.POST['Name']
        email = request.POST['Email']
        contact = request.POST['Phone']
        pass1 = request.POST['Password']
        cpass2 = request.POST['Confirm_Password']

        try :
            user = StudentModelRegistration.objects.get(Email = email)
            form = {}
            form["key"] = StudentFormRegistration
            return render(request, "app1/registration.html",  {"formdata" : form, "data" : "Email Already Exists","btn" : "RLol"})
        except :
            form = {}
            form["key"] = LoginForm
            StudentModelRegistration.objects.create(Name  = name,
                                                Phone = contact,
                                                Email = email,
                                                Password = pass1,
                                                Confirm_Password = cpass2)
            return render(request, "app1/login.html", {"formdata" : form,"btn" : "RLol"})
    else :
        print("Outside")
    return render (request, "app1/index.html",{"btn" : "RLol"})


def logindatapage(request):
    if request.POST:
        email = request.POST['Email']
        passw = request.POST['Password']
        try :
            user = StudentModelRegistration.objects.get(Email = email)
            if user.Password == passw:                
                user_name = user.Name
                request.session['NAME'] = user_name
                request.session['EMAIL'] = user.Email
                form = {}
                form['key'] = StudentQueryForm


                return render(request, "app1/dashboard.html", {"formdata" : form, "name" : user_name, "mail" : email, "btn" : ""})
                
            else :
                form = {}
                form['key'] = LoginForm
                return render(request, "app1/login.html", {"data" : "Invalid Password ", "formdata" : form,"btn" : "RLol"})
        except :
            form = {}
            form['key'] = LoginForm
            return render(request, "app1/login.html", {"data" : "username not match","btn" : "RLol", "formdata" : form})
    else :
        print("Data need in Post Method")
    return render(request, "app1/index.html", {"btn" : "RLol"})


def dashpage(request):
    form = {}
    form['key'] = StudentQueryForm
    user_name = request.session['NAME']
    user_email = request.session['EMAIL']
    user = StudentModelRegistration.objects.get(Email = user_email)
    email = user.Email
    return render(request, "app1/dashboard.html", {"formdata" : form, "name" : user_name, "mail" : email, "btn" : ""})



def querydatapage(request):
    if request.POST:
        email = request.POST['Query_Email']
        sub = request.POST['Query_Subject']
        query = request.POST['Query']
        userMail = request.POST['qsubmitbtn']
        Current_Data = datetime.datetime.now()
        if email == userMail:
            StudentQuery.objects.create(Query_Email = email,
                                            Query_Sub = sub,
                                            QueryDate = Current_Data,
                                            Query_Query = query)
            return redirect("/dash")
        else :
            form = {}
            form['key'] = StudentQueryForm 
            user_name = request.session['NAME']
            return render(request, "app1/dashboard.html", {"formdata" : form, "name" : user_name, "mail" : email, "btn" : "", "msg" : "Account Email and Provided Email Should be match"})
        
def shawtabledatabtnpage(request):
    global tabledata
    if request.POST:
        email = request.POST['btnemail']
        allData = StudentQuery.objects.all().filter(Query_Email = email)
        form = {}
        form['key'] = StudentQueryForm        
        user_name = request.session['NAME']

        return render(request, "app1/dashboard.html", {"formdata" : form, "name" : user_name, "mail" : email, "btn" : "", "tabledata" :allData})
    else :
        pass


def EditDeleteDatapage(request):
    if request.POST:
        try:
            print("EDIT ID =============== ", editId)
            editId = request.POST['editbtn']
            form = {}
            form['key'] = StudentQueryForm
            print("********************KEYS****************")
            for i in form.keys:
                print(i)
            # print(form.keys)
            return HttpResponse("EDIT")
        
        except :
            print("DELETE ID =============== ", deleteId)
            deleteId = request.POST['deletebtn']
            StudentQuery.objects.all().filter(id = deleteId).delete()
            
            user_email = request.session['EMAIL']
            user_name = request.session['NAME']
            allData = StudentQuery.objects.all().filter(Query_Email = user_email)
            form = {}
            form['key'] = StudentQueryForm
            return render(request, "app1/dashboard.html", {"formdata" : form, "name" : user_name, "mail" : user_email, "btn" : "", "tabledata" :allData})

app/templates/app1/about.html
{% extends "app1/base.html" %}

{% block Content %}
    <h1> About page {{name}} </h1> 
{% endblock  %}

app/templates/app1/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
   
    <style>
      * {
        padding: 0;
        margin: 0;
        box-sizing: border-box;
        overflow-x: hidden;
        text-decoration: none;
      }
      .nav_data {
        display: flex;
        justify-content: space-between;
        flex-wrap: wrap;
        flex-direction: row;
        line-height: 50px;
        font-size: 20px;
        cursor: pointer;
      }
      ul {
        display: flex;
      }
      ul li {
        margin: 0 10px;
      }
      
      form {
        width: 550px;
        margin: auto;
        font-size: 20px;
        margin-top: 50px;
      }
      form h1 {
        text-align: center;
        margin-bottom: 20px;
      }
      form label {
        display: inline-block;
        width: 170px;
      }
      form input {
        width: 300px;
        display: inline-block;
        margin: 10px;
        font-size: 20px;
        padding: 5px 10px;
        outline: none;
      }
      .buttons_form {
        width: 100%;
        text-align: center;
      }
      button {
        width: 200px;
        padding: 5px 10px;
        cursor: pointer;
        font-weight: 800;
        font-size: 20px;
        font-family :'Lucida Sans', 'Lucida Sans Regular', 'Lucida Grande', 'Lucida Sans Unicode', Geneva, Verdana, sans-serif;
        margin: 20px 0;
      }
     
      .dash .firsth1 {
        text-align: center;
        font-size: 25px;
        font-family: 'Courier New', Courier, monospace;
        background-color: cornflowerblue;
        line-height: 50px;
      }
      #id_Query {
        height: 100px;
        width: 300px;
        margin: auto;
        padding: 10px;
        font-size: 20px;
        margin-left: 10px;
      }
      table {
        max-width: 1000px;
      }
      table tr td, th{
        padding: 10px;
        overflow-x: hidden;
        width: 100px;
      }
    </style>
  </head>

  <body>
    <section>
      <nav style="width: 90vw; margin: auto;">
        <div class="nav_data">
          <div>
            <a href="{% url '' %}">Home</a>
          </div>
          <ul>
            <li>
              <a href="{% url 'home' %}">Home</a>
            </li>
            <li>
              <a href="{% url 'about' %}">About</a>
            </li>
            <li>
              <a href="{% url 'service' %}">Service</a>
            </li>
            <li>
              <a href="{% url 'contact' %}">Contact</a>
            </li>
          </ul>

          <ul>
            {% if btn == "RLol" %}
            <li>
              <a href="{% url 'register' %}">Registration</a>
            </li>
            <li>
              <a href="{% url 'login' %}">Login</a>
            </li>
            {% endif %}
            {% if btn == "" %}
            <li>
              <a href="{% url 'dash' %}">Profile</a>
            </li>
            <li>
              <a href="{% url 'logout' %}">Logout</a>
            </li>
            {% endif %}
          </ul>
        </div>
      </nav>
    </section>

    <section style="min-height: 500px; background-color: aquamarine;">
      {% block Content %}

      {% endblock %}
    </section>

    <section style="height: 100px; background-color :brown;">FOOTER</section>
  </body>
</html>

app/templates/app1/contact.html
{% extends "app1/base.html" %}

{% block Content %}
    <h1> Contact page {{name}} </h1> 
{% endblock  %}

app/templates/app1/dashboard.html
{% extends "app1/base.html" %}

{% block Content %}
<section class="dash">
    <h1 class="firsth1"> Dashboard</h1>
    <div style="width: 90%; margin: auto;">
        <h2 align="right"> Name {{name}} </h2>
        <div style="display: flex; justify-content: space-between; flex-wrap: wrap;">
            <div class="leftboard">
                Left
                <h2>Write Your Query {{mail}} </h2>

                
                <form action="{% url 'querydata' %}" method="post">
                    {% csrf_token %}
                    <div style="color: red;" > {{msg}} </div>
                    {{formdata.key}}
                    <div class="buttons_form">
                        <button name="qsubmitbtn" value={{mail}}> Query Submit </button>
                    </div>
                </form>



                <div class="buttons_form">
                    <form action="{% url 'shawtabledatabtn' %}" method="post">
                        {% csrf_token %}
                        <button name="btnemail" value={{mail}}>All Your Query </button>
                    </form>
                    {% if tabledata %}
                    <table border="1">
                        <tr>
                            <th> Email </th>
                            <th> Subject </th>
                            <th> Post Date </th>
                            <th style="width: 280px;"> Data </th>
                            <th> Edit </th>
                            <th> Detele </th>
                        </tr>
                        <form action="{% url 'EditDeleteData' %}" method="post" class="editdeleteDataClass" >
                            
                            {% for i in tabledata %}
                            {% csrf_token %}
                            <tr>
                                <td> {{i.Query_Email}} </td>
                                <td> {{i.Query_Sub}} </td>
                                <td> {{i.QueryDate}} </td>
                                <td> {{i.Query_Query}} </td>
                                <td>
                                    <button style="padding: 5px 10px; width: fit-content; font-size: 15px; " name="editbtn" value={{i.id}}>Edit</button> 
                                </td>
                                <td> 
                                    <button style="padding: 5px 10px; width: fit-content; font-size: 15px; " name="deletebtn" value={{i.id}} >Delete</button>
                                </td>
                            </tr>
                        </form>
                        {% endfor %}
                    </table>
                    {% endif %}
                </div>
            </div>
            <div class="rightboard">
                Right

            </div>
        </div>
    </div>
</section>
{% endblock %}

app/templates/app1/index.html
{% extends "app1/base.html" %}

{% block Content %}
    <h1> Home page {{name}} </h1> 
{% endblock  %}

app/templates/app1/login.html
{% extends "app1/base.html" %}

{% block Content %}
<form action="{% url 'logindata' %}" method="post">
    {% csrf_token %}
    <h1> Login page </h1> 
    <h2> {{data}} </h2>
    {{formdata.key}}

    <div class="buttons_form">
        <button> Login </button>
    </div>
</form>    

{% endblock  %}

app/templates/app1/registration.html
{% extends "app1/base.html" %}

{% block Content %}
    <form method="post" action="{% url 'registerdata' %}" >
        {% csrf_token %}
        <h1> Registration </h1>
        <h2 style="color: red;"> {{data}} </h2>
        {{formdata.key}}
        <div class="buttons_form">
            <button> Registration </button>
        </div>
    </form>
{% endblock  %}

app/templates/app1/service.html
{% extends "app1/base.html" %}

{% block Content %}
    <h1> Service page {{name}} </h1> 
{% endblock  %}